// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace BrowserLinkInspector
{
    internal sealed partial class Vsix
    {
        public const string Id = "e607008b-f079-4e79-8d23-1d8c5dba1626";
        public const string Name = "Browser Link Inspector 2019";
        public const string Description = @"Adds inspect and debug mode directly in the browsers";
        public const string Language = "en-US";
        public const string Version = "0.5";
        public const string Author = "Mads Kristensen";
        public const string Tags = "browser link";
    }
}
